#!/usr/bin/expect -f
set port [lindex $argv 0]
set user_host [lindex $argv 1]
set password [lindex $argv 2]
set local_path [lindex $argv 3]
set remote_path [lindex $argv 4]
set exclude_file [lindex $argv 5]

set timeout 1800
spawn rsync -avz --delete --exclude-from=$exclude_file -e "ssh -p $port" $local_path $user_host:$remote_path
expect {
    "yes/no" {
        send "yes\r"
        exp_continue
    }
    "password:" {
        send "$password\r"
    }
}
expect eof
